import { motion } from 'motion/react';
import { FileText, ArrowLeft, Shield, AlertTriangle, Scale, Lock } from 'lucide-react';
import { Button } from './ui/button';

interface DisclaimerPageProps {
  onBack: () => void;
}

export function DisclaimerPage({ onBack }: DisclaimerPageProps) {
  return (
    <div className="min-h-screen">
      {/* Header */}
      <motion.header
        initial={{ y: -20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        className="border-b border-white/20 backdrop-blur-sm bg-white/40 sticky top-0 z-30"
      >
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="icon" className="rounded-full" onClick={onBack}>
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-indigo-600 to-purple-600 flex items-center justify-center">
                <FileText className="w-5 h-5 text-white" />
              </div>
              <span className="text-lg font-semibold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
                Oky-Docky
              </span>
            </div>
          </div>
        </div>
      </motion.header>

      <div className="container mx-auto px-4 py-16 max-w-3xl">
        {/* Title */}
        <motion.div initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} className="mb-12">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-slate-100 to-slate-200 flex items-center justify-center">
              <Scale className="w-6 h-6 text-slate-600" />
            </div>
            <div>
              <h1 className="text-3xl font-bold">Terms of Service & Disclaimer</h1>
              <p className="text-sm text-slate-500">Last updated: February 2026</p>
            </div>
          </div>
        </motion.div>

        <div className="space-y-10">
          {/* Important Notice */}
          <motion.div
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ delay: 0.1 }}
            className="bg-amber-50 border-2 border-amber-200 rounded-2xl p-6"
          >
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-6 h-6 text-amber-600 flex-shrink-0 mt-0.5" />
              <div>
                <h2 className="text-lg font-bold text-amber-800 mb-2">Important Notice</h2>
                <p className="text-amber-700 leading-relaxed">
                  Oky-Docky is a <strong>document preparation tool</strong> operated by <strong>Barckhat LLC</strong>,
                  not a tax advisory service. We do not provide tax, legal, financial, or accounting advice.
                  The information and forms generated by this service are based solely on the data you provide.
                  Always consult a qualified tax professional for advice specific to your situation.
                </p>
              </div>
            </div>
          </motion.div>

          {/* Sections */}
          <Section
            icon={Shield}
            title="1. Service Description"
            delay={0.15}
            content={[
              'Oky-Docky is a product of Barckhat LLC. It provides an automated document preparation service that helps users fill out IRS tax forms (such as W-9, W-4, Form 14039, and others) through a guided question-and-answer interface.',
              'The service generates pre-filled PDF documents based on user-provided information. Barckhat LLC does not verify, validate, or guarantee the accuracy, completeness, or legal sufficiency of any form generated.',
              'Barckhat LLC is not a registered tax preparation firm. We do not file forms on your behalf unless explicitly stated in a separate paid service agreement.',
            ]}
          />

          <Section
            icon={AlertTriangle}
            title="2. User Responsibility & Assumption of Risk"
            delay={0.2}
            content={[
              'YOU ARE SOLELY AND EXCLUSIVELY RESPONSIBLE for the accuracy, completeness, and legality of all information you enter into this service. Barckhat LLC acts only as a technology provider and bears no responsibility for the content of your submissions.',
              'YOU ARE SOLELY RESPONSIBLE for reviewing, verifying, signing, filing, and submitting all generated documents. Any errors, omissions, or inaccuracies in the data you provide are entirely your responsibility.',
              'YOU ASSUME ALL RISK and liability for any tax penalties, fines, legal consequences, audits, or other outcomes resulting from the use of documents generated by this service. Barckhat LLC shall not be held liable for any consequences arising from your use of generated forms.',
              'You acknowledge that tax laws are complex and subject to change. It is your responsibility to ensure that the forms you generate comply with current IRS regulations and applicable state and federal laws.',
              'You agree to not use this service for any fraudulent, illegal, or deceptive purpose, including but not limited to identity theft, tax evasion, or filing false documents.',
            ]}
          />

          <Section
            icon={Scale}
            title="3. Limitation of Liability"
            delay={0.25}
            content={[
              'TO THE MAXIMUM EXTENT PERMITTED BY LAW, BARCKHAT LLC, ITS MEMBERS, MANAGERS, OFFICERS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THIS SERVICE.',
              'This includes, without limitation: errors in generated forms, penalties or fines imposed by the IRS or any government agency, missed filing deadlines, incorrect tax calculations, rejected returns, identity theft consequences, or any financial loss resulting from reliance on forms generated by this service.',
              'Barckhat LLC provides this service on an "AS IS" and "AS AVAILABLE" basis, without warranties of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement.',
              'The total liability of Barckhat LLC for any claim arising from use of the service shall not exceed the amount you paid for the service in the 12 months preceding the claim, or $100, whichever is less.',
              'By using this service, you agree to indemnify and hold harmless Barckhat LLC from any claims, damages, losses, or expenses (including attorney fees) arising from your use of the service or any forms generated through it.',
            ]}
          />

          <Section
            icon={Lock}
            title="4. Privacy & Data Handling"
            delay={0.3}
            content={[
              'We take your privacy seriously. Sensitive information (such as Social Security Numbers and Employer Identification Numbers) is processed in memory only and is not stored on our servers after your PDF is generated.',
              'We do not sell, share, or distribute your personal information to third parties.',
              'Generated PDF files are created on-demand and delivered directly to your browser. We do not retain copies of completed forms.',
              'You are responsible for the security of downloaded documents on your own devices.',
            ]}
          />

          <Section
            icon={Shield}
            title="5. IRS & Regulatory Disclaimer"
            delay={0.35}
            content={[
              'Oky-Docky and Barckhat LLC are not affiliated with, endorsed by, or connected to the Internal Revenue Service (IRS) or any government agency.',
              'IRS form templates used in this service are based on publicly available IRS publications. Form versions and field structures may change; we make reasonable efforts to keep templates current but do not guarantee they reflect the latest revisions.',
              'For official IRS forms, instructions, and publications, visit www.irs.gov.',
            ]}
          />

          <Section
            icon={Scale}
            title="6. Acceptance of Terms"
            delay={0.4}
            content={[
              'By using Oky-Docky, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service and Disclaimer.',
              'We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the revised terms.',
              'If you do not agree with these terms, please do not use the service.',
            ]}
          />
        </div>

        {/* Footer */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
          className="mt-16 text-center text-sm text-slate-500 border-t border-slate-200 pt-8"
        >
          <p>Questions about our terms? Contact us at legal@barckhat.com</p>
          <p className="mt-2">&copy; 2026 Barckhat LLC. All rights reserved. Oky-Docky is a product of Barckhat LLC.</p>
        </motion.div>
      </div>
    </div>
  );
}

function Section({ icon: Icon, title, content, delay }: { icon: any; title: string; content: string[]; delay: number }) {
  return (
    <motion.div
      initial={{ y: 20, opacity: 0 }}
      animate={{ y: 0, opacity: 1 }}
      transition={{ delay }}
    >
      <div className="flex items-center gap-2 mb-4">
        <Icon className="w-5 h-5 text-indigo-600" />
        <h2 className="text-xl font-bold text-slate-800">{title}</h2>
      </div>
      <div className="space-y-3 pl-7">
        {content.map((paragraph, i) => (
          <p key={i} className="text-slate-600 leading-relaxed">{paragraph}</p>
        ))}
      </div>
    </motion.div>
  );
}
